name: bop
description: The Vennue design system
version: 0.0.1
homepage: https://github.com/vennueapp/bop

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^4.0.4
  material_color_utilities: ^0.2.0
  plugin_platform_interface: ^2.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
