name: build

on: push

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
    - run: dart format --output=show --set-exit-if-changed .
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.10.0
      with:
          flutter-version: '3.10.x'
          channel: 'stable'
    - run: flutter analyze
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.10.0
      with:
          flutter-version: '3.10.x'
          channel: 'stable'
    - run: flutter pub get
    - run: flutter test
  tag:
    name: Tag
    needs: [format, analyze, test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jacopocarlini/action-autotag@stable
      with:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        tag_prefix: 'v'
